# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.0
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-app
  name: postgres-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-app

